


#POSTGRES 
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/banktransfer

#FlyWay
quarkus.flyway.migrate-at-start=true

#Kafka
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.transferencias-out.connector=smallrye-kafka
mp.messaging.outgoing.transferencias-out.topic=transferencias
mp.messaging.incoming.transferencias-in.connector=smallrye-kafka
mp.messaging.incoming.transferencias-in.topic=transferencias

#jwt
mp.jwt.verify.issuer=banktransfer
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem


#oidc
quarkus.oidc.auth-server-url=http://localhost:8080/realms/banreservas-realm
quarkus.oidc.client-id=transfer-api
quarkus.oidc.application-type=service


#Quarkus server
quarkus.http.port=8081


#redis
quarkus.redis.hosts=redis://localhost:6379


quarkus.cache.redis.transferencias-detalle.value-type=org.acme.Transfer
quarkus.cache.redis.transferencias-lista.value-type=[Lorg.acme.Transfer;
quarkus.cache.redis.transferencias-lista.expire-after-write=5M
quarkus.cache.redis.transferencias-detalle.expire-after-write=5M

quarkus.cache.redis.transferencias-lista.value-type=java.util.List