


#POSTGRES 
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/banktransfer

#FlyWay
quarkus.flyway.migrate-at-start=true

#Kafka
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.transferencias-out.connector=smallrye-kafka
mp.messaging.outgoing.transferencias-out.topic=transferencias
mp.messaging.incoming.transferencias-in.connector=smallrye-kafka
mp.messaging.incoming.transferencias-in.topic=transferencias

#jwt
mp.jwt.verify.issuer=banktransfer
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem


